### ISSUE TITLE
Replace fetchJson.request usage to this.request

### ISSUE THREAD

**Issue by hemantsonu20** [center-key/fetch-json#10]
**Current code**
```javascript
get:    (url, params,   options) => fetchJson.request('GET',    url, params,   options),
```

**Updated code**
```javascript
get:    (url, params,   options) => this.request('GET',    url, params,   options),
```

**Comment by dpilafian** [comment]
The JavaScript keyword `this` can create confusion.  It seem clearer to explicitly reference `fetchJson`.

What would be the advantages of switching to `this`?

**Comment by hemantsonu20** [comment]
Nothing much advantage here. 
`this` syntax looks clean to me as it clearly indicates that called method (`request` via `this.request`) exists in the same object. `fetchJson.request` gives sense that it exists somewhere else.
