### ISSUE TITLE
Upgrade to ES6 spread operator to handle default options in fetch-json.js

### ISSUE THREAD

**Issue by dpilafian** [center-key/fetch-json#11]
For improved readability, change:
```javascript
Object.assign(settings, options);
```
to:
```javascript
const settings = { ...defaults, ...options };
```

And then rename the `settings` object on line 8 to `defaults`:
https://github.com/center-key/fetch-json/blob/master/fetch-json.js#L8

**Comment by AprilShenk** [comment]
I would like to attempt this for hacktoberfest. Can you please assign it to me?

**Comment by prikshitsetia** [comment]
Hey, I would like to work on this issue
