### ISSUE TITLE
Replace deprecated assert.deepEqual() in spec/jsdom.js

### ISSUE THREAD

**Issue by dpilafian** [center-key/fetch-json#15]
The function `assert.deepEqual()` has been deprecated.

Replace all occurrences in **spec/jsdom.js** with:
`assert.deepStrictEqual()`

See:
https://github.com/center-key/fetch-json/blob/master/spec/jsdom.js#L27

**Comment by talhaabbasi** [comment]
Hi, can I work on this?

**Comment by talhaabbasi** [comment]
Please add the labels `hacktoberfest-accepted` to the PR if you accept it
![Screenshot from 2020-10-12 09-12-24](https://user-images.githubusercontent.com/28659121/95704781-66c2ab80-0c6b-11eb-9d13-6c26d7dc579a.png)
