### ISSUE TITLE
Switch to trailing comma style for multiline arrays and objects in spec/node.js

### ISSUE THREAD

**Issue by dpilafian** [center-key/fetch-json#20]
Including a comma for the last item in **multiline** arrays and objects makes the code more consistent and easier to edit.  The consistency helps reduce merge diffs.

See example line in **spec/node.js** that needs a trailing comma:
https://github.com/center-key/fetch-json/blob/master/spec/node.js#L36

**Comment by fluentinstroll** [comment]
Good morning! Can I fix this issue?
