### ISSUE TITLE
Upgrade to ES6 spread operator to merge options in fetch-json.js

### ISSUE THREAD

**Issue by dpilafian** [center-key/fetch-json#7]
For improved readability, change:
```javascript
Object.assign(settings, options);
```
to:
```javascript
const settings = { ...defaults, ...options };
```

**Comment by hemantsonu20** [comment]
Can I work on this

**Comment by dpilafian** [comment]
It takes about an hour to create each issue that has the **"good first issue"** label.  These special issues give new developers an opportunity to practice submitting open source PRs and help to bring additional contributors into the project.

The issues labeled **"good first issue"** are for first-time contributors.

However, here are 3 other projects you can submit PRs for:
1. https://github.com/center-key/clabe-validator/issues
1. https://github.com/dnajs/dna.js/issues
1. https://github.com/center-key/pretty-print-json/issues

See the **Contributor notes** at:
[README.md](../#readme)
